<Project>
  <!-- Propiedades comunes a TODOS los proyectos de la solución -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NeutralLanguage>es-MX</NeutralLanguage>
    <!-- Solo español/inglés: reduce mucho el tamaño de la publicación/instalador. -->
    <SatelliteResourceLanguages>es;en</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
